### ISSUE TITLE
Specified analyze path does not exist: /root/abc/def/asd/asd_asd/utils.py

### ISSUE THREAD

**Issue by cyb3rsalih** [protectai/vulnhuntr#7]
Firstly thank you for this awesome project. Hope I make some contribution to this project for languages I know. 

I built and run the docker image as 
docker run --rm --name vulnhuntr-container vulnhuntr -r /root/abc -l claude -a def/asd/asd_asd/utils.py -v

``Traceback (most recent call last):
  File "/usr/local/bin/vulnhuntr", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/vulnhuntr/__main__.py", line 321, in run
    files_to_analyze = repo.get_files_to_analyze(Path(args.root) / analyze_path)
  File "/usr/local/lib/python3.10/site-packages/vulnhuntr/__main__.py", line 270, in get_files_to_analyze
    raise FileNotFoundError(f"Specified analyze path does not exist: {path_to_analyze}")
FileNotFoundError: Specified analyze path does not exist: /root/abc/def/asd/asd_asd/utils.py``

Then 
I tried `cat /root/abc/def/asd/asdasd/utils.py` I can see the content.

What should I do?

**Comment by DanMcInerney** [comment]
docker run --rm -e ANTHROPIC_API_KEY=sk-1234 -v /local/path/to/target/repo:/repo vulnhuntr:latest -r /repo -l claude -v

**Comment by cyb3rsalih** [comment]
Great it worked. We may add this to readme also

**Comment by DanMcInerney** [comment]
Yup I put a PR to add it to readme
